config/routes.rb
Rails.application.routes.draw do
  root to: "home#index"
  devise_for :users
  resources :users
  resources :shops do
    resources :likes, only:[:create, :destroy]
    resources :reviews, only:[:create,:destroy]
  end

  end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user
    belongs_to :shop
    validates_uniqueness_of :shop_id, scope: :user_id
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  belongs_to :shop

  validates :content, presence: true  
end

app/models/shop.rb
class Shop < ApplicationRecord
    geocoded_by :address
    after_validation :geocode, if: :address_changed?

    belongs_to :user
    has_many :likes, dependent: :destroy
    has_many :reviews, dependent: :destroy
    mount_uploaders :images, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :shops, dependent: :destroy
  has_many :likes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  mount_uploader :image, AvatarUploader

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base    
    before_action :configure_permitted_parameters, if: :devise_controller?

    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:sign_up, keys: [:name, :image])
    end

    def after_sign_in_path_for(resource)
        user_path(current_user) # ログイン後に遷移するpathを設定
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
    def create
        @like=Like.new(user_id:current_user.id, shop_id:params[:shop_id])
        @like.save
        redirect_back(fallback_location: root_path)
    end

    def destroy
        @like=Like.find_by(user_id:current_user.id, shop_id:params[:shop_id])
        @like.destroy
        redirect_back(fallback_location: root_path)
    end

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  def create
    # ログインユーザーのみがコメントできる
    @shop = Shop.find(params[:shop_id])
    @review = current_user.reviews.new(review_params)
    
    if @review.save
      redirect_to shop_path(@shop)
    
    else
      render 'shops/show'
    end
  end

  def destroy
    @shop = Shop.find(params[:shop_id])
    review=current_user.reviews.find(params[:id])
    review.destroy
    redirect_to shop_path(@shop)
  end
  
  private

  def review_params
    params.require(:review).permit(:content).merge(shop_id: params[:shop_id]) #①
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @shops=Shop.all
  end

  def new
    @shop=Shop.new
    @review=Review.new
  end

  def show
    @shop=Shop.find_by(id:params[:id])
    @reviews = @shop.reviews
    @review = Review.new
  end

  def create
    @shop=Shop.new(shop_params)
    @shop.user_id=current_user.id
    if @shop.save
      flash[:notice] ="投稿しました"
      redirect_to shops_path
    else
      render action: :new
    end
  end

  def edit
    @shop = Shop.find(params[:id])
    if @shop.user != current_user
        redirect_to shops_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @shop = Shop.find(params[:id])
    if @shop.update(shop_params)
      redirect_to shop_path(@shop), notice: "お店を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    shop = Shop.find(params[:id])
    shop.destroy
    redirect_to shops_path, notice: "削除しました。"
  end
  


  def shop_params
    params.require(:shop).permit(:name, :body, :address, :latitude, :longitude, :evaluation,{images: [] })
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users=User.all
  end

  def show
    @user=User.find_by(id:params[:id])
    @shops=Shop.where(user_id:@user.id)
    @likes=Like.where(user_id:@user.id)
  end

  def edit
    @user=User.find_by(id:params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find_by(id:params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  def destroy
    @user=User.find_by(id:params[:id]).destroy
    if @user.destroy
      flash[:success] = "User deleted"
      redirect_to users_path
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :email, :image)
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<section class="hero is-info is-fullheight">
            <div class="hero-body">
                <div class="container has-text-centered">
                    <div class="column is-6 is-offset-3">
                        <h1 class="title is-size-1" style="font-family: Comic Sans MS;">
                            GurumeBook
                        </h1>
                        <h2 class="subtitle">
                            お気に入りのお店をシェアしよう
                        </h2>
                        <div class="columns is-centered">
                            <div class="column is-5">
                                <br>
                            <%= link_to "ログイン", new_user_session_path, class: "button is-fullwidth" %>
                                <br>
                            <%= link_to "新規登録", new_user_registration_path, class: "button  is-fullwidth" %>
                            </div>
                        </div>
                        </div>
                    </div>
                </div>
            </div>

    </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
    <head>
      <title>GurumeBook</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>

      <meta name="viewport" content="width=device-width, initial-scale=1.0">

      <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.min.css" integrity="sha256-UzFD2WYH2U1dQpKDjjZK72VtPeWP50NoJjd26rnAdUI=" crossorigin="anonymous" />
      <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
      <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    </head>

    <body>
      <% if flash[:notice] %>
        <div class="notification is-info">
          <p class="notice"><%= notice %></p>
        </div>
      <% end %>

      <% if flash[:alert] %>
        <div class="notification is-danger">
          <p class="alert"><%= alert %></p>
        </div>
      <% end %>

      <nav class="navbar has-background-black">
          <div class="navbar-brand">
            <%= link_to root_path, class: "navbar-item has-text-white" do %>
            <h1 class="title has-text-white" style="font-family: cursive;">GurumeBook</h1>
            <% end %>
              
            <%if user_signed_in?%> 
              <p class="navbar-item has-text-white">ようこそ<%=current_user.name%>さん!</p>
            <%end%> 

            <a role="button" class="navbar-burger burger has-background-black" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
              <span aria-hidden="true"></span>
            </a>
          </div>

          <%if user_signed_in?%>   
            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-end">
                <div class="navbar-item">
                  <%= link_to("マイページ", user_path(current_user),class:"has-text-white") %>
                </div>
                <div class="navbar-item">
                  <%= link_to("ユーザー一覧", users_path, class:"has-text-white") %> 
                </div>
                <div class="navbar-item">
                  <%= link_to("投稿一覧", shops_path,class:"has-text-white") %>
                </div>
                <div class="navbar-item">
                  <%= link_to("新規投稿", new_shop_path,class:"has-text-white") %>
                </div>
                <div class="navbar-item">
                  <%= link_to("ログアウト", destroy_user_session_path, method: :delete,class:"has-text-white") %>
                </div>
              </div>
            </div>

           <%else%>


            <div id="navbarBasicExample" class="navbar-menu">
              <div class="navbar-end">
                <div class="navbar-item">
                  <%= link_to("ユーザー一覧", users_path, class:"has-text-white") %> 
                </div>
                <div class="navbar-item">
                  <%= link_to("投稿一覧", shops_path,class:"has-text-white") %>
                </div>
                <div class="navbar-item">
                  <%= link_to("新規登録", new_user_registration_path,class:"has-text-white") %>
                </div>
                <div class="navbar-item">
                  <%= link_to("ログイン", new_user_session_path,class:"has-text-white") %>
                </div>
              </div>
            </div>

          <%end%>

        </nav>


    <script type="text/javascript">
        document.querySelector('.navbar-burger').addEventListener("click", toggleNav);
        function toggleNav() {
              var nav = document.querySelector('.navbar-menu');
              if(nav.className == "navbar-menu") {
                  nav.className = "navbar-menu is-active has-background-black";
              } else {
                  nav.className = "navbar-menu";
              }
        }
    </script>


      
    <%= yield %>

 
  </body>
</html>

app/views/reviews/index.html.erb
<h1>Reviews#index</h1>
<p>Find me in app/views/reviews/index.html.erb</p>

app/views/shops/edit.html.erb
<section class="hero has-background-black is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                  <p class="subtitle">編集</p>
                  <div class="box">
                    <%= form_for @shop do |f| %>
                      <div class="field">
                        <%= f.label :title, "店名", class: "label" %>
                        <%= f.text_field :name, class: "input" %>
                      </div>

                      <div class="field">
                        <%= f.label :body, "感想", class: "label" %>
                        <%= f.text_area :body, class: "textarea" %>
                      </div>

                      <div class="field">
                        <%= f.label :写真 %>
                        <%= f.file_field :images, multiple: true %>
                      </div>

                      <div class="field">
                        <%= f.label :address, "住所", class: "label" %>
                        <%= f.text_area :address, class: "input" %>
                      </div>

                      <div id="evaluate_stars">
                        <label>評価</label>
                      </div>

                      <%= f.submit '投稿', class: "button is-black" %>
                    <% end %>
                  </div>
                </div>
            </div>
          </div>
</section>

<script>
          $('#evaluate_stars').raty({
            starOn: "<%= asset_path('star-on.png') %>",
            starOff: "<%= asset_path('star-off.png') %>",
            starHalf: "<%= asset_path('star-half.png') %>",
            scoreName: 'shop[evaluation]' //登録するモデル名とカラム名を記述
          });
</script>

app/views/shops/index.html.erb
<section class="section has-background-black">
        <div class="container has-text-centered">
            <div class="columns is-multiline" style="padding: 2rem">
            <% @shops.each do |shop| %>
                <div class="column is-3 ">
                    <div class="card">
                        <div class="card-image">
                            <figure class="image is-4by3">
                              <% shop.images.each do |image| %>
                                <%= link_to shop_path(shop) do %>
                                  <%=image_tag image.to_s%>
                                <% end %>
                              <% end %>
                            </figure>
                        </div>

                        <div class="card-content">
                          <div class="card-content">
                            <div class="content">
                                <h2><%= shop.name %></h2>
                                <p class="shop-evaluation" data-score="<%=shop.evaluation %>"></p>  
                                <%=link_to "詳細", shop_path(shop),class: "button is-black"%>
                            </div>
                        　</div>
                      　</div>
                    </div>
                </div>
            <% end %>
            </div>
        </div>
        </div>
    </section>


<script>
  $('.shop-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/shops/new.html.erb
<section class="hero has-background-black is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
                <div class="column is-4 is-offset-4">
                  <strong class="title is-size-1" style="font-family: Comic Sans MS;">GurumeBook</strong>
                      <hr class="login-hr">
                      <p class="subtitle">お店をシェアする</p>
                      <div class="box">

                        <%= form_for @shop do |f| %>
                          <div class="field">
                            <%= f.label :name, "店名", class: "label" %>
                            <%= f.text_field :name, class: "input" %>
                          </div>

                          <div class="field">
                            <%= f.label :body, "感想", class: "label" %>
                            <%= f.text_area :body, class: "textarea" %>
                          </div>

                          <div class="field">
                            <%= f.label :写真 %>
                            <%= f.file_field :images, multiple: true %>
                          </div>

                          <div class="field">
                            <%= f.label :address, "住所", class: "label" %>
                            <%= f.text_area :address, class: "input" %>
                          </div>

                          <div id="evaluate_stars">
                            <label>評価</label>
                          </div>

                        
                          <%= f.submit '投稿', class: "button is-success" %>
                        <% end %>
                      </div>
                  </div>
            </div>
          </div>
</section>

<script>
    $('#evaluate_stars').raty({
      starOn: "<%= asset_path('star-on.png') %>",
      starOff: "<%= asset_path('star-off.png') %>",
      starHalf: "<%= asset_path('star-half.png') %>",
      scoreName: 'shop[evaluation]' //登録するモデル名とカラム名を記述
    });
</script>

    

app/views/shops/show.html.erb
<section class="section has-background-black">
  <div class="container">
      <div class="columns is-centered">
      <div class="column is-7">
        <div class="card">
          <div class="card-content">
            <div class="media">
              <div class="media-content">
                <p class="shopname is-size-4"><%= @shop.name %></p>
                <p class="shop-evaluation" data-score="<%=@shop.evaluation %>"></p>
              </div>
            </div>
            <div class="content">
                  <div id="map"></div>
                </div>
            <div class="content">
              <% @shop.images.each do |image| %>
                <%=image_tag image.to_s%>
              <% end %>
              <% if Like.find_by(user_id:current_user.id, shop_id:@shop.id)%>
                <p><%= link_to shop_like_path(@shop), method: :delete, class:"like" do%></p>
                  <i class="fas fa-heart"></i>
                <% end %>
                 <%= @shop.likes.count %>
                
              <% else %>
                <p><%= link_to shop_likes_path(@shop), method: :review,class:"like" do%></p>
                  <i class="fas fa-heart"></i>
                <% end %>
                <%= @shop.likes.count %>
              <% end %>
            </div>

            <div class="content">
              <table class="table is-narrow">
                <tr>
                  <th>感想</th>
                </tr>
                <tr>
                  <td><%= simple_format @shop.body %></td>
                </tr>
              </table>
              <% if @shop.user.id == current_user.id %>
                <%= link_to "編集画面へ", edit_shop_path(@shop), class: "button is-success" %>
                <%= link_to "削除", shop_path(@shop), method: :delete,class: "button is-black"%>
              <% end %>
            </div>
          </div>
        </div>
      </div>

      <div class="column is-4">
          <article class="panel is-link">
            <p class="panel-heading">
              By <%= @shop.user.name %>
            </p>
            
            <%= link_to user_path(@shop.user), class: "panel-block" do %>
              <span class="panel-icon">
                <i class="fas fa-user" aria-hidden="true"></i>
              </span>
              <%= @shop.user.name %> さんのページへ
            <% end %>
          </article>

          <h2 class="has-text-white">コメント一覧</h2>
            <% @shop.reviews.each do |review| %>
              <div class="has-text-white"> 
                <%= review.content %>
                <hr>
              </div>
              <% if review.user == current_user %>
                <div>
                    <%= link_to '削除', [@shop, review], method: :delete %>
                </div>
              <% end %>
            <% end %>

            <%= form_with model: [@shop, @review], local: true do |f| %>
              <div class="field">
                <%= f.text_field :content, class: 'input' %>
              </div>
                <%= f.submit class: 'button is-dark' %>
            <% end %>
       </div>
      </div>
  </div>
  <%= link_to 'Back', shops_path, class:"has-text-white" %>
</section>






<script type="text/javascript">
    function initMap() {

        var test ={lat: <%= @shop.latitude %>, lng: <%= @shop.longitude %>};
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: test
        });
        var transitLayer = new google.maps.TransitLayer();
        transitLayer.setMap(map);

        var contentString = '住所：<%= @shop.address %>';
        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });

        var marker = new google.maps.Marker({
            position:test,
            map: map,
            title: contentString
        });

        marker.addListener('click', function() {
            infowindow.open(map, marker);
        });
    }
</script>

<script async defer
        src="https://maps.googleapis.com/maps/api/js?v=3.exp&key=AIzaSyAafClNH0jxMHeNSabrL4onyejsurfeRm8&callback=initMap">
</script>

<style type="text/css">
  #map { height: 400px;
    margin-left:auto;
    margin-right:auto;
    text-align:left;
    width: 80%;}
</style>


<script>
  $('.shop-evaluation').raty({
    readOnly: true,
    score: function() {
      return $(this).attr('data-score');
    },
    path: '/assets/'
  });
</script>

app/views/users/edit.html.erb
<section class="hero has-background-black is-fullheight">
        <div class="hero-body">
            <div class="container has-text-centered">
              <div class="column is-4 is-offset-4">
                <p class="subtitle">プロフィール編集</p>
                  <div class="box">
                    <%= form_for @user do |f| %>
                      <div class="field">
                        <%= f.label :name, "ユーザー名", class: "label" %>
                        <%= f.text_field :name, class: "input" %>
                      </div>

                      <div class="field">
                        <%= f.label :email, "メールアドレス", class: "label" %>
                        <%= f.email_field :email, class: "input" %>
                      </div>


                      <div class="field">
                        <%= f.label :image, "プロフィール画像", class: "label" %>
                        <%= f.file_field :image, class: "input" %>
                      </div>

                      <%= f.submit "更新", class: "button is-black" %>
                      <%= link_to "退会",user_path(current_user.id), class: "button is-black", method: :delete, "data-confirm" => "本当に退会しますか？" %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>
</section>

app/views/users/index.html.erb
<section class="section has-background-black">
  <div class="container">
    <div class="columns is-multiline">
      <% @users.each do |user| %>
        <div class="column is-3">
          <div class="card">
            <div class="card-image">
              <figure class="image">
                <%= link_to user_path(user) do %>
                <% if user.image? %>
                  <%= image_tag user.image.url, class: "user-icon" %>
                  <% else %>
                  <%= image_tag "default.png", alt: "user-icon",  class: "user-icon" %>
                  <% end %>
                <% end %>
              </figure>
            </div>
            
            <div class="card-content">
               <div class="media">
                  <div class="media-content">
                    <div class="title"><%=link_to user.name, user_path(user) %></div>
                  </div>
               </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>  

app/views/users/new.html.erb
<h1>Users#new</h1>
<p>Find me in app/views/users/new.html.erb</p>

app/views/users/show.html.erb
<section class="section">
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-8">
        <div class="columns is-centered">
          <div class="column is-4">
            <figure class="image is-128x128"  style="margin-left: auto; margin-right: auto;">
              <% if @user.image? %>
        　      <%= image_tag @user.image.url, class: "user-icon" %>
              <% else %>
                <%= image_tag "default.png", alt: "user-icon", size: "200", class: "user-icon" %>
              <% end %>
            </figure>
          </div>
          <div class="column is-8">
            <table class="table is-fullwidth">
              <tr>
                <td class="is-size-4">
                  <strong><%= @user.name %></strong>
                </td>
                <% if @user.id == current_user.id %>
                <td class="is-size-4">
                  <%= @user.email %>
                </td>
                <td>
                    <%= link_to "編集", edit_user_path(@user), class: "button is-primary" %>
                </td>
                <% end %>
              </tr>
            </table>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
  <h2 class="is-size-3">シェアしたお店</h2>
    <div class="columns is-multiline">
      <% @user.shops.each do |shop| %>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
              <% shop.images.each do |image| %>
                <%= link_to shop_path(shop) do %>
                  <%=image_tag image.to_s%>
                  <% end %>
                <% end %>
              </figure>
            </div>
            <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to shop_path(shop), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このお店を見る
                  <% end %>
                  <% if @user.id == current_user.id %>
                    <%= link_to edit_shop_path(shop), class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-edit"></i>
                      </span>
                      このお店を編集する
                    <% end %>
                    <%= link_to shop_path(shop), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                      <span class="panel-icon">
                        <i class="fas fa-trash"></i>
                      </span>
                      このお店を削除する
                    <% end %>
                  <% end %>
                </div>
              </div>
            </div>
              
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>

<section class="section">
  <div class="container">
  <h2 class="is-size-3">気になるお店</h2>
    <div class="columns is-multiline">
      <%@likes.each do |like|%>
        <div class="column is-4">
          <div class="card">
            <div class="card-image">
              <figure class="image is-4by3">
              <% shop=Shop.find_by(id:like.shop_id)%>
                <% shop.images.each do |image| %>
                <%= link_to shop_path(shop) do %>
                  <%=image_tag image.to_s%>
                  <% end %>
                <% end %>
              </figure>
            </div>
          </div>
          <div class="card-content">
              <div class="media">
                <div class="media-content">
                  <%= link_to shop_path(shop), class: "panel-block" do %>
                    <span class="panel-icon">
                      <i class="fas fa-book" aria-hidden="true"></i>
                    </span>
                    このお店を見る
                  <% end %>
                  
                </div>
              </div>
            </div>


        </div>
      <% end %>
    </div>
  </div>
</section>
      

            